[theme]
# primary accent color for interactive elements
primaryColor = "https://github.com/Jpaku93/Digital_CV/blob/main/assets/BGImage.jpg"

# Background color for the main content area
backgroundColor = "#002b36"

# background color for the side bar and most interactive widgetrs
secondaryBackgroundColor = "#586e75"

# Color used for almost all text
textColor = "#fff"
